// API route for country codes
import { NextResponse } from "next/server";

export interface CountryCode {
  code: string;
  country: string;
  flag: string;
  name: string;
}

const countryCodes: CountryCode[] = [
  { code: "+1", country: "🇺🇸 United States", flag: "🇺🇸", name: "United States" },
  { code: "+1", country: "🇨🇦 Canada", flag: "🇨🇦", name: "Canada" },
  { code: "+7", country: "🇷🇺 Russia", flag: "🇷🇺", name: "Russia" },
  { code: "+20", country: "🇪🇬 Egypt", flag: "🇪🇬", name: "Egypt" },
  { code: "+27", country: "🇿🇦 South Africa", flag: "🇿🇦", name: "South Africa" },
  { code: "+30", country: "🇬🇷 Greece", flag: "🇬🇷", name: "Greece" },
  { code: "+31", country: "🇳🇱 Netherlands", flag: "🇳🇱", name: "Netherlands" },
  { code: "+32", country: "🇧🇪 Belgium", flag: "🇧🇪", name: "Belgium" },
  { code: "+33", country: "🇫🇷 France", flag: "🇫🇷", name: "France" },
  { code: "+34", country: "🇪🇸 Spain", flag: "🇪🇸", name: "Spain" },
  { code: "+36", country: "🇭🇺 Hungary", flag: "🇭🇺", name: "Hungary" },
  { code: "+39", country: "🇮🇹 Italy", flag: "🇮🇹", name: "Italy" },
  { code: "+40", country: "🇷🇴 Romania", flag: "🇷🇴", name: "Romania" },
  { code: "+41", country: "🇨🇭 Switzerland", flag: "🇨🇭", name: "Switzerland" },
  { code: "+43", country: "🇦🇹 Austria", flag: "🇦🇹", name: "Austria" },
  { code: "+44", country: "🇬🇧 United Kingdom", flag: "🇬🇧", name: "United Kingdom" },
  { code: "+45", country: "🇩🇰 Denmark", flag: "🇩🇰", name: "Denmark" },
  { code: "+46", country: "🇸🇪 Sweden", flag: "🇸🇪", name: "Sweden" },
  { code: "+47", country: "🇳🇴 Norway", flag: "🇳🇴", name: "Norway" },
  { code: "+48", country: "🇵🇱 Poland", flag: "🇵🇱", name: "Poland" },
  { code: "+49", country: "🇩🇪 Germany", flag: "🇩🇪", name: "Germany" },
  { code: "+51", country: "🇵🇪 Peru", flag: "🇵🇪", name: "Peru" },
  { code: "+52", country: "🇲🇽 Mexico", flag: "🇲🇽", name: "Mexico" },
  { code: "+53", country: "🇨🇺 Cuba", flag: "🇨🇺", name: "Cuba" },
  { code: "+54", country: "🇦🇷 Argentina", flag: "🇦🇷", name: "Argentina" },
  { code: "+55", country: "🇧🇷 Brazil", flag: "🇧🇷", name: "Brazil" },
  { code: "+56", country: "🇨🇱 Chile", flag: "🇨🇱", name: "Chile" },
  { code: "+57", country: "🇨🇴 Colombia", flag: "🇨🇴", name: "Colombia" },
  { code: "+58", country: "🇻🇪 Venezuela", flag: "🇻🇪", name: "Venezuela" },
  { code: "+60", country: "🇲🇾 Malaysia", flag: "🇲🇾", name: "Malaysia" },
  { code: "+61", country: "🇦🇺 Australia", flag: "🇦🇺", name: "Australia" },
  { code: "+62", country: "🇮🇩 Indonesia", flag: "🇮🇩", name: "Indonesia" },
  { code: "+63", country: "🇵🇭 Philippines", flag: "🇵🇭", name: "Philippines" },
  { code: "+64", country: "🇳🇿 New Zealand", flag: "🇳🇿", name: "New Zealand" },
  { code: "+65", country: "🇸🇬 Singapore", flag: "🇸🇬", name: "Singapore" },
  { code: "+66", country: "🇹🇭 Thailand", flag: "🇹🇭", name: "Thailand" },
  { code: "+81", country: "🇯🇵 Japan", flag: "🇯🇵", name: "Japan" },
  { code: "+82", country: "🇰🇷 South Korea", flag: "🇰🇷", name: "South Korea" },
  { code: "+84", country: "🇻🇳 Vietnam", flag: "🇻🇳", name: "Vietnam" },
  { code: "+86", country: "🇨🇳 China", flag: "🇨🇳", name: "China" },
  { code: "+90", country: "🇹🇷 Turkey", flag: "🇹🇷", name: "Turkey" },
  { code: "+91", country: "🇮🇳 India", flag: "🇮🇳", name: "India" },
  { code: "+92", country: "🇵🇰 Pakistan", flag: "🇵🇰", name: "Pakistan" },
  { code: "+93", country: "🇦🇫 Afghanistan", flag: "🇦🇫", name: "Afghanistan" },
  { code: "+94", country: "🇱🇰 Sri Lanka", flag: "🇱🇰", name: "Sri Lanka" },
  { code: "+95", country: "🇲🇲 Myanmar", flag: "🇲🇲", name: "Myanmar" },
  { code: "+98", country: "🇮🇷 Iran", flag: "🇮🇷", name: "Iran" },
  { code: "+212", country: "🇲🇦 Morocco", flag: "🇲🇦", name: "Morocco" },
  { code: "+213", country: "🇩🇿 Algeria", flag: "🇩🇿", name: "Algeria" },
  { code: "+216", country: "🇹🇳 Tunisia", flag: "🇹🇳", name: "Tunisia" },
  { code: "+218", country: "🇱🇾 Libya", flag: "🇱🇾", name: "Libya" },
  { code: "+220", country: "🇬🇲 Gambia", flag: "🇬🇲", name: "Gambia" },
  { code: "+221", country: "🇸🇳 Senegal", flag: "🇸🇳", name: "Senegal" },
  { code: "+222", country: "🇲🇷 Mauritania", flag: "🇲🇷", name: "Mauritania" },
  { code: "+223", country: "🇲🇱 Mali", flag: "🇲🇱", name: "Mali" },
  { code: "+224", country: "🇬🇳 Guinea", flag: "🇬🇳", name: "Guinea" },
  { code: "+225", country: "🇨🇮 Ivory Coast", flag: "🇨🇮", name: "Ivory Coast" },
  { code: "+226", country: "🇧🇫 Burkina Faso", flag: "🇧🇫", name: "Burkina Faso" },
  { code: "+227", country: "🇳🇪 Niger", flag: "🇳🇪", name: "Niger" },
  { code: "+228", country: "🇹🇬 Togo", flag: "🇹🇬", name: "Togo" },
  { code: "+229", country: "🇧🇯 Benin", flag: "🇧🇯", name: "Benin" },
  { code: "+230", country: "🇲🇺 Mauritius", flag: "🇲🇺", name: "Mauritius" },
  { code: "+231", country: "🇱🇷 Liberia", flag: "🇱🇷", name: "Liberia" },
  { code: "+232", country: "🇸🇱 Sierra Leone", flag: "🇸🇱", name: "Sierra Leone" },
  { code: "+233", country: "🇬🇭 Ghana", flag: "🇬🇭", name: "Ghana" },
  { code: "+234", country: "🇳🇬 Nigeria", flag: "🇳🇬", name: "Nigeria" },
  { code: "+235", country: "🇹🇩 Chad", flag: "🇹🇩", name: "Chad" },
  {
    code: "+236",
    country: "🇨🇫 Central African Republic",
    flag: "🇨🇫",
    name: "Central African Republic",
  },
  { code: "+237", country: "🇨🇲 Cameroon", flag: "🇨🇲", name: "Cameroon" },
  { code: "+238", country: "🇨🇻 Cape Verde", flag: "🇨🇻", name: "Cape Verde" },
  { code: "+239", country: "🇸🇹 Sao Tome and Principe", flag: "🇸🇹", name: "Sao Tome and Principe" },
  { code: "+240", country: "🇬🇶 Equatorial Guinea", flag: "🇬🇶", name: "Equatorial Guinea" },
  { code: "+241", country: "🇬🇦 Gabon", flag: "🇬🇦", name: "Gabon" },
  { code: "+242", country: "🇨🇬 Congo", flag: "🇨🇬", name: "Congo" },
  { code: "+243", country: "🇨🇩 Congo (DRC)", flag: "🇨🇩", name: "Congo (DRC)" },
  { code: "+244", country: "🇦🇴 Angola", flag: "🇦🇴", name: "Angola" },
  { code: "+245", country: "🇬🇼 Guinea-Bissau", flag: "🇬🇼", name: "Guinea-Bissau" },
  {
    code: "+246",
    country: "🇮🇴 British Indian Ocean Territory",
    flag: "🇮🇴",
    name: "British Indian Ocean Territory",
  },
  { code: "+247", country: "🇦🇨 Ascension Island", flag: "🇦🇨", name: "Ascension Island" },
  { code: "+248", country: "🇸🇨 Seychelles", flag: "🇸🇨", name: "Seychelles" },
  { code: "+249", country: "🇸🇩 Sudan", flag: "🇸🇩", name: "Sudan" },
  { code: "+250", country: "🇷🇼 Rwanda", flag: "🇷🇼", name: "Rwanda" },
  { code: "+251", country: "🇪🇹 Ethiopia", flag: "🇪🇹", name: "Ethiopia" },
  { code: "+252", country: "🇸🇴 Somalia", flag: "🇸🇴", name: "Somalia" },
  { code: "+253", country: "🇩🇯 Djibouti", flag: "🇩🇯", name: "Djibouti" },
  { code: "+254", country: "🇰🇪 Kenya", flag: "🇰🇪", name: "Kenya" },
  { code: "+255", country: "🇹🇿 Tanzania", flag: "🇹🇿", name: "Tanzania" },
  { code: "+256", country: "🇺🇬 Uganda", flag: "🇺🇬", name: "Uganda" },
  { code: "+257", country: "🇧🇮 Burundi", flag: "🇧🇮", name: "Burundi" },
  { code: "+258", country: "🇲🇿 Mozambique", flag: "🇲🇿", name: "Mozambique" },
  { code: "+260", country: "🇿🇲 Zambia", flag: "🇿🇲", name: "Zambia" },
  { code: "+261", country: "🇲🇬 Madagascar", flag: "🇲🇬", name: "Madagascar" },
  { code: "+262", country: "🇷🇪 Reunion", flag: "🇷🇪", name: "Reunion" },
  { code: "+263", country: "🇿🇼 Zimbabwe", flag: "🇿🇼", name: "Zimbabwe" },
  { code: "+264", country: "🇳🇦 Namibia", flag: "🇳🇦", name: "Namibia" },
  { code: "+265", country: "🇲🇼 Malawi", flag: "🇲🇼", name: "Malawi" },
  { code: "+266", country: "🇱🇸 Lesotho", flag: "🇱🇸", name: "Lesotho" },
  { code: "+267", country: "🇧🇼 Botswana", flag: "🇧🇼", name: "Botswana" },
  { code: "+268", country: "🇸🇿 Swaziland", flag: "🇸🇿", name: "Swaziland" },
  { code: "+269", country: "🇰🇲 Comoros", flag: "🇰🇲", name: "Comoros" },
  { code: "+290", country: "🇸🇭 Saint Helena", flag: "🇸🇭", name: "Saint Helena" },
  { code: "+291", country: "🇪🇷 Eritrea", flag: "🇪🇷", name: "Eritrea" },
  { code: "+297", country: "🇦🇼 Aruba", flag: "🇦🇼", name: "Aruba" },
  { code: "+298", country: "🇫🇴 Faroe Islands", flag: "🇫🇴", name: "Faroe Islands" },
  { code: "+299", country: "🇬🇱 Greenland", flag: "🇬🇱", name: "Greenland" },
  { code: "+350", country: "🇬🇮 Gibraltar", flag: "🇬🇮", name: "Gibraltar" },
  { code: "+351", country: "🇵🇹 Portugal", flag: "🇵🇹", name: "Portugal" },
  { code: "+352", country: "🇱🇺 Luxembourg", flag: "🇱🇺", name: "Luxembourg" },
  { code: "+353", country: "🇮🇪 Ireland", flag: "🇮🇪", name: "Ireland" },
  { code: "+354", country: "🇮🇸 Iceland", flag: "🇮🇸", name: "Iceland" },
  { code: "+355", country: "🇦🇱 Albania", flag: "🇦🇱", name: "Albania" },
  { code: "+356", country: "🇲🇹 Malta", flag: "🇲🇹", name: "Malta" },
  { code: "+357", country: "🇨🇾 Cyprus", flag: "🇨🇾", name: "Cyprus" },
  { code: "+358", country: "🇫🇮 Finland", flag: "🇫🇮", name: "Finland" },
  { code: "+359", country: "🇧🇬 Bulgaria", flag: "🇧🇬", name: "Bulgaria" },
  { code: "+370", country: "🇱🇹 Lithuania", flag: "🇱🇹", name: "Lithuania" },
  { code: "+371", country: "🇱🇻 Latvia", flag: "🇱🇻", name: "Latvia" },
  { code: "+372", country: "🇪🇪 Estonia", flag: "🇪🇪", name: "Estonia" },
  { code: "+373", country: "🇲🇩 Moldova", flag: "🇲🇩", name: "Moldova" },
  { code: "+374", country: "🇦🇲 Armenia", flag: "🇦🇲", name: "Armenia" },
  { code: "+375", country: "🇧🇾 Belarus", flag: "🇧🇾", name: "Belarus" },
  { code: "+376", country: "🇦🇩 Andorra", flag: "🇦🇩", name: "Andorra" },
  { code: "+377", country: "🇲🇨 Monaco", flag: "🇲🇨", name: "Monaco" },
  { code: "+378", country: "🇸🇲 San Marino", flag: "🇸🇲", name: "San Marino" },
  { code: "+380", country: "🇺🇦 Ukraine", flag: "🇺🇦", name: "Ukraine" },
  { code: "+381", country: "🇷🇸 Serbia", flag: "🇷🇸", name: "Serbia" },
  { code: "+382", country: "🇲🇪 Montenegro", flag: "🇲🇪", name: "Montenegro" },
  { code: "+383", country: "🇽🇰 Kosovo", flag: "🇽🇰", name: "Kosovo" },
  { code: "+385", country: "🇭🇷 Croatia", flag: "🇭🇷", name: "Croatia" },
  { code: "+386", country: "🇸🇮 Slovenia", flag: "🇸🇮", name: "Slovenia" },
  {
    code: "+387",
    country: "🇧🇦 Bosnia and Herzegovina",
    flag: "🇧🇦",
    name: "Bosnia and Herzegovina",
  },
  { code: "+389", country: "🇲🇰 North Macedonia", flag: "🇲🇰", name: "North Macedonia" },
  { code: "+420", country: "🇨🇿 Czech Republic", flag: "🇨🇿", name: "Czech Republic" },
  { code: "+421", country: "🇸🇰 Slovakia", flag: "🇸🇰", name: "Slovakia" },
  { code: "+423", country: "🇱🇮 Liechtenstein", flag: "🇱🇮", name: "Liechtenstein" },
  { code: "+500", country: "🇫🇰 Falkland Islands", flag: "🇫🇰", name: "Falkland Islands" },
  { code: "+501", country: "🇧🇿 Belize", flag: "🇧🇿", name: "Belize" },
  { code: "+502", country: "🇬🇹 Guatemala", flag: "🇬🇹", name: "Guatemala" },
  { code: "+503", country: "🇸🇻 El Salvador", flag: "🇸🇻", name: "El Salvador" },
  { code: "+504", country: "🇭🇳 Honduras", flag: "🇭🇳", name: "Honduras" },
  { code: "+505", country: "🇳🇮 Nicaragua", flag: "🇳🇮", name: "Nicaragua" },
  { code: "+506", country: "🇨🇷 Costa Rica", flag: "🇨🇷", name: "Costa Rica" },
  { code: "+507", country: "🇵🇦 Panama", flag: "🇵🇦", name: "Panama" },
  {
    code: "+508",
    country: "🇵🇲 Saint Pierre and Miquelon",
    flag: "🇵🇲",
    name: "Saint Pierre and Miquelon",
  },
  { code: "+509", country: "🇭🇹 Haiti", flag: "🇭🇹", name: "Haiti" },
  { code: "+590", country: "🇬🇵 Guadeloupe", flag: "🇬🇵", name: "Guadeloupe" },
  { code: "+591", country: "🇧🇴 Bolivia", flag: "🇧🇴", name: "Bolivia" },
  { code: "+592", country: "🇬🇾 Guyana", flag: "🇬🇾", name: "Guyana" },
  { code: "+593", country: "🇪🇨 Ecuador", flag: "🇪🇨", name: "Ecuador" },
  { code: "+594", country: "🇬🇫 French Guiana", flag: "🇬🇫", name: "French Guiana" },
  { code: "+595", country: "🇵🇾 Paraguay", flag: "🇵🇾", name: "Paraguay" },
  { code: "+596", country: "🇲🇶 Martinique", flag: "🇲🇶", name: "Martinique" },
  { code: "+597", country: "🇸🇷 Suriname", flag: "🇸🇷", name: "Suriname" },
  { code: "+598", country: "🇺🇾 Uruguay", flag: "🇺🇾", name: "Uruguay" },
  { code: "+599", country: "🇳🇱 Netherlands Antilles", flag: "🇳🇱", name: "Netherlands Antilles" },
  { code: "+670", country: "🇹🇱 East Timor", flag: "🇹🇱", name: "East Timor" },
  { code: "+672", country: "🇦🇶 Antarctica", flag: "🇦🇶", name: "Antarctica" },
  { code: "+673", country: "🇧🇳 Brunei", flag: "🇧🇳", name: "Brunei" },
  { code: "+674", country: "🇳🇷 Nauru", flag: "🇳🇷", name: "Nauru" },
  { code: "+675", country: "🇵🇬 Papua New Guinea", flag: "🇵🇬", name: "Papua New Guinea" },
  { code: "+676", country: "🇹🇴 Tonga", flag: "🇹🇴", name: "Tonga" },
  { code: "+677", country: "🇸🇧 Solomon Islands", flag: "🇸🇧", name: "Solomon Islands" },
  { code: "+678", country: "🇻🇺 Vanuatu", flag: "🇻🇺", name: "Vanuatu" },
  { code: "+679", country: "🇫🇯 Fiji", flag: "🇫🇯", name: "Fiji" },
  { code: "+680", country: "🇵🇼 Palau", flag: "🇵🇼", name: "Palau" },
  { code: "+681", country: "🇼🇫 Wallis and Futuna", flag: "🇼🇫", name: "Wallis and Futuna" },
  { code: "+682", country: "🇨🇰 Cook Islands", flag: "🇨🇰", name: "Cook Islands" },
  { code: "+683", country: "🇳🇺 Niue", flag: "🇳🇺", name: "Niue" },
  { code: "+684", country: "🇦🇸 American Samoa", flag: "🇦🇸", name: "American Samoa" },
  { code: "+685", country: "🇼🇸 Samoa", flag: "🇼🇸", name: "Samoa" },
  { code: "+686", country: "🇰🇮 Kiribati", flag: "🇰🇮", name: "Kiribati" },
  { code: "+687", country: "🇳🇨 New Caledonia", flag: "🇳🇨", name: "New Caledonia" },
  { code: "+688", country: "🇹🇻 Tuvalu", flag: "🇹🇻", name: "Tuvalu" },
  { code: "+689", country: "🇵🇫 French Polynesia", flag: "🇵🇫", name: "French Polynesia" },
  { code: "+690", country: "🇹🇰 Tokelau", flag: "🇹🇰", name: "Tokelau" },
  { code: "+691", country: "🇫🇲 Micronesia", flag: "🇫🇲", name: "Micronesia" },
  { code: "+692", country: "🇲🇭 Marshall Islands", flag: "🇲🇭", name: "Marshall Islands" },
  { code: "+850", country: "🇰🇵 North Korea", flag: "🇰🇵", name: "North Korea" },
  { code: "+852", country: "🇭🇰 Hong Kong", flag: "🇭🇰", name: "Hong Kong" },
  { code: "+853", country: "🇲🇴 Macau", flag: "🇲🇴", name: "Macau" },
  { code: "+855", country: "🇰🇭 Cambodia", flag: "🇰🇭", name: "Cambodia" },
  { code: "+856", country: "🇱🇦 Laos", flag: "🇱🇦", name: "Laos" },
  { code: "+880", country: "🇧🇩 Bangladesh", flag: "🇧🇩", name: "Bangladesh" },
  { code: "+886", country: "🇹🇼 Taiwan", flag: "🇹🇼", name: "Taiwan" },
  { code: "+960", country: "🇲🇻 Maldives", flag: "🇲🇻", name: "Maldives" },
  { code: "+961", country: "🇱🇧 Lebanon", flag: "🇱🇧", name: "Lebanon" },
  { code: "+962", country: "🇯🇴 Jordan", flag: "🇯🇴", name: "Jordan" },
  { code: "+963", country: "🇸🇾 Syria", flag: "🇸🇾", name: "Syria" },
  { code: "+964", country: "🇮🇶 Iraq", flag: "🇮🇶", name: "Iraq" },
  { code: "+965", country: "🇰🇼 Kuwait", flag: "🇰🇼", name: "Kuwait" },
  { code: "+966", country: "🇸🇦 Saudi Arabia", flag: "🇸🇦", name: "Saudi Arabia" },
  { code: "+967", country: "🇾🇪 Yemen", flag: "🇾🇪", name: "Yemen" },
  { code: "+968", country: "🇴🇲 Oman", flag: "🇴🇲", name: "Oman" },
  { code: "+970", country: "🇵🇸 Palestine", flag: "🇵🇸", name: "Palestine" },
  { code: "+971", country: "🇦🇪 United Arab Emirates", flag: "🇦🇪", name: "United Arab Emirates" },
  { code: "+972", country: "🇮🇱 Israel", flag: "🇮🇱", name: "Israel" },
  { code: "+973", country: "🇧🇭 Bahrain", flag: "🇧🇭", name: "Bahrain" },
  { code: "+974", country: "🇶🇦 Qatar", flag: "🇶🇦", name: "Qatar" },
  { code: "+975", country: "🇧🇹 Bhutan", flag: "🇧🇹", name: "Bhutan" },
  { code: "+976", country: "🇲🇳 Mongolia", flag: "🇲🇳", name: "Mongolia" },
  { code: "+977", country: "🇳🇵 Nepal", flag: "🇳🇵", name: "Nepal" },
  { code: "+992", country: "🇹🇯 Tajikistan", flag: "🇹🇯", name: "Tajikistan" },
  { code: "+993", country: "🇹🇲 Turkmenistan", flag: "🇹🇲", name: "Turkmenistan" },
  { code: "+994", country: "🇦🇿 Azerbaijan", flag: "🇦🇿", name: "Azerbaijan" },
  { code: "+995", country: "🇬🇪 Georgia", flag: "🇬🇪", name: "Georgia" },
  { code: "+996", country: "🇰🇬 Kyrgyzstan", flag: "🇰🇬", name: "Kyrgyzstan" },
  { code: "+998", country: "🇺🇿 Uzbekistan", flag: "🇺🇿", name: "Uzbekistan" },
];

export async function GET() {
  try {
    return NextResponse.json({
      success: true,
      data: countryCodes,
      count: countryCodes.length,
    });
  } catch (error) {
    console.error("❌ Error fetching country codes:", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch country codes" },
      { status: 500 }
    );
  }
}
