/// <reference lib="webworker" />

import { clientsClaim } from "workbox-core";
import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";

declare const self: ServiceWorkerGlobalScope;

// Claim all clients immediately
clientsClaim();

// Precache all static assets generated by Next.js
precacheAndRoute(self.__WB_MANIFEST || []);

// Cache strategies for different types of requests
const cacheFirstStrategy = new CacheFirst({
  cacheName: "static-assets-v1",
  plugins: [
    new ExpirationPlugin({
      maxEntries: 100,
      maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
    }),
  ],
});

const networkFirstStrategy = new NetworkFirst({
  cacheName: "api-responses-v1",
  plugins: [
    new ExpirationPlugin({
      maxEntries: 50,
      maxAgeSeconds: 60 * 5, // 5 minutes
    }),
  ],
});

const staleWhileRevalidateStrategy = new StaleWhileRevalidate({
  cacheName: "dynamic-content-v1",
  plugins: [
    new ExpirationPlugin({
      maxEntries: 100,
      maxAgeSeconds: 60 * 60 * 24 * 7, // 7 days
    }),
  ],
});

// Register routes with different strategies
registerRoute(
  ({ request }) => request.destination === "script" || request.destination === "style",
  cacheFirstStrategy
);

registerRoute(({ request }) => request.destination === "image", cacheFirstStrategy);

registerRoute(({ url }) => url.pathname.startsWith("/api/"), networkFirstStrategy);

registerRoute(({ request }) => request.destination === "document", staleWhileRevalidateStrategy);

// Background sync for offline actions
// Note: Using manual background sync handling instead of the plugin for more control

// Handle background sync
// eslint-disable-next-line @typescript-eslint/no-explicit-any
self.addEventListener("sync", (event: any) => {
  if (event.tag === "background-sync") {
    event.waitUntil(handleBackgroundSync());
  }
});

async function handleBackgroundSync(): Promise<void> {
  try {
    // Notify the main thread that background sync is starting
    const clients = await self.clients.matchAll();
    clients.forEach((client) => {
      client.postMessage({
        type: "BACKGROUND_SYNC",
        status: "starting",
      });
    });

    // Here you would implement your sync logic
    // For now, we'll just simulate a successful sync
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // Notify completion
    clients.forEach((client) => {
      client.postMessage({
        type: "BACKGROUND_SYNC",
        status: "completed",
      });
    });
  } catch (error) {
    console.error("Background sync failed:", error);
    const clients = await self.clients.matchAll();
    clients.forEach((client) => {
      client.postMessage({
        type: "BACKGROUND_SYNC",
        status: "failed",
        error: error instanceof Error ? error.message : "Unknown error",
      });
    });
  }
}

// Push notification handling
self.addEventListener("push", (event: PushEvent) => {
  if (!event.data) return;

  const data = event.data.json();

  const options: NotificationOptions = {
    body: data.body || "You have a new notification",
    icon: data.icon || "/favicon.ico",
    badge: data.badge || "/favicon.ico",
    data: data.url || "/",
    requireInteraction: true,
    silent: false,
  };

  event.waitUntil(self.registration.showNotification(data.title || "ForeverPages", options));
});

// Handle notification clicks
self.addEventListener("notificationclick", (event: NotificationEvent) => {
  event.notification.close();

  if (event.action === "dismiss") {
    return;
  }

  // Default action or "view" action
  const urlToOpen = event.notification.data || "/";

  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((clients) => {
      // Check if there's already a window/tab open with the target URL
      const existingClient = clients.find(
        (client) => client.url === urlToOpen || client.url.startsWith(urlToOpen)
      );

      if (existingClient) {
        // Focus the existing window/tab
        return existingClient.focus();
      } else {
        // Open a new window/tab
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Handle messages from the main thread
self.addEventListener("message", (event: ExtendableMessageEvent) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

// Install event
self.addEventListener("install", () => {
  console.log("Service Worker installing");
  self.skipWaiting();
});

// Activate event
self.addEventListener("activate", (event: ExtendableEvent) => {
  console.log("Service Worker activating");
  event.waitUntil(self.clients.claim());
});
